name: API tests

on:
  push:
    branches: [ main ]
  pull_request:
  # расписание: каждый день в 06:00 UTC (в Варшаве будет +- 07:00/08:00 в зависимости от сезона)
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
